### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by AndreaVitale** [manojdcoder/titanium-mupdf#17]
Hi, I have OutOfMemory exception problems after several times I open a pdf.
Here is the exception log:

```
[ERROR] art: Throwing OutOfMemoryError "Failed to allocate a 10899468 byte allocation with 4613041 free bytes and 4MB until OOM"
[ERROR] TiApplication: (main) [427,83483] Sending event: exception on thread: main msg:java.lang.OutOfMemoryError: Failed to allocate a 10899468 byte allocation with 4613041 free bytes and 4MB until OOM; Titanium 5.0.2,2015/09/30 12:07,92c2265
[ERROR] TiApplication: java.lang.OutOfMemoryError: Failed to allocate a 10899468 byte allocation with 4613041 free bytes and 4MB until OOM
[ERROR] TiApplication:  at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
[ERROR] TiApplication:  at android.graphics.Bitmap.nativeCreate(Native Method)
[ERROR] TiApplication:  at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
[ERROR] TiApplication:  at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
[ERROR] TiApplication:  at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
[ERROR] TiApplication:  at com.artifex.mupdflib.PageView.<init>(PageView.java:140)
[ERROR] TiApplication:  at com.artifex.mupdflib.MuPDFPageView.<init>(MuPDFPageView.java:123)
[ERROR] TiApplication:  at com.artifex.mupdflib.MuPDFPageAdapter.getView(MuPDFPageAdapter.java:43)
[ERROR] TiApplication:  at com.artifex.mupdflib.ReaderView.getOrCreateChild(ReaderView.java:843)
[ERROR] TiApplication:  at com.artifex.mupdflib.ReaderView.onLayout(ReaderView.java:717)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
[ERROR] TiApplication:  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
[ERROR] TiApplication:  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
[ERROR] TiApplication:  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
[ERROR] TiApplication:  at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at com.slidingmenu.lib.CustomViewAbove.onLayout(CustomViewAbove.java:476)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[INFO]  TiApplication:  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
[ERROR] TiApplication:  at android.view.View.layout(View.java:15596)
[ERROR] TiApplication:  at android.view.ViewGroup.layout(ViewGroup.java:4966)
[ERROR] TiApplication:  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
[ERROR] TiApplication:  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
[ERROR] TiApplication:  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
[ERROR] TiApplication:  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
[ERROR] TiApplication:  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
[ERROR] TiApplication:  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
[ERROR] TiApplication:  at android.view.Choreographer.doFrame(Choreographer.java:550)
[ERROR] TiApplication:  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
[ERROR] TiApplication:  at android.os.Handler.handleCallback(Handler.java:739)
[ERROR] TiApplication:  at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] TiApplication:  at android.os.Looper.loop(Looper.java:135)
[ERROR] TiApplication:  at android.app.ActivityThread.main(ActivityThread.java:5221)
[ERROR] TiApplication:  at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication:  at java.lang.reflec
```

Have you just solved this?

**Comment by mano-mykingdom** [comment]
Do you still face this issue, If then can you please give a detailed test case? I recommend you to try the latest version of the module which resolves several crash issues.

**Comment by manojdcoder** [comment]
Closing this one due to inactivity.
